# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MaskReminder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaskReminder
  pod 'Firebase/Analytics'
  pod 'Alamofire', '~> 5.2'

  target 'MaskReminderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MaskReminderUITests' do
    # Pods for testing
  end

end
